version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  commands:
    - pip install mkdocs mkdocs-material mkdocs-redirects
    - cat mkdocs.yml
    - mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file mkdocs.yml

mkdocs:
  configuration: mkdocs.yml