name: Build distribution

'on':
  workflow_call:
    inputs:
      os:
        description: "Operating system"
        required: true
        type: string
      python-version:
        description: "Python version"
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: "Run CI"
    uses: ./.github/workflows/ci.yml
    with:
      os: ${{ inputs.os }}
      python-version: ${{ inputs.python-version }}

  build:
    name: "Build distribution"
    runs-on: ${{ inputs.os }}
    needs: ci
    steps:
      - uses: asottile/workflows/.github/actions/fast-checkout@v1.8.1

      - uses: ./.github/actions/install-dependencies
        with:
          python-version: ${{ inputs.python-version }}

      - name: "Run uv build"
        run: uv build

      - name: "Upload build artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ inputs.python-version }}-${{ inputs.os }}
          path: "**/dist/"
