name: CI
'on':
  - push
jobs:
  lock-file:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-cached-uv
      - run: uv lock --locked

  linting:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs:
      - lock-file
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-cached-uv
      - run: uvx ruff check .

  type-checking:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs:
      - lock-file
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-cached-uv
      - run: uv run basedpyright --level ERROR

  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs:
      - lock-file
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-cached-uv
      - run: uv run pytest --cov

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs:
      - linting
      - type-checking
      - tests
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-cached-uv
      - run: uv build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}
          path: dist/
