name: Publish to PyPI

'on':
  release:
    types:
      - created

defaults:
  run:
    shell: bash

jobs:
  publish:
    name: "Publishing dist"
    runs-on: ubuntu-latest
    steps:
      - uses: asottile/workflows/.github/actions/fast-checkout@v1.8.1

      - uses: ./.github/actions/install-dependencies
        with:
          python-version: "3.13"

      - name: "Build distribution"
        run: uv build

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: "**/dist/"
