name: PR

'on':
  pull_request:
    branches:
    - tba
    - dev
    - main

defaults:
  run:
    shell: bash

jobs:
  pre-commit:
    name: "Run pre-commit"
    runs-on: ubuntu-latest
    steps:
      - uses: asottile/workflows/.github/actions/fast-checkout@v1.8.1

      - name: Install uv and dependencies
        uses: ./.github/actions/install-dependencies
        with:
          python-version: "3.13"

      - name: Load pre-commit cache
        id: cache-pre-commit
        uses: actions/cache@v4
        env:
          cache-name: cache-pre-commit
        with:
          key: ${{ env.cache-name }}-${{ hashFiles('**/.pre-commit-config.yaml', '~/.cache/pre-commit/*') }}
          path: ~/.cache/pre-commit

      - name: Run pre-commit
        run: uv run pre-commit run --all-files --color=always

      - uses: pre-commit/action@v3.0.1
      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()
