name: Push build

on:
  push:
    branches:
      - dev
      - main

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest

    uses: ./.github/workflows/lint-and-test.yml
    with:
      os: ${{ matrix.os }}
