name: Release to PyPI

'on':
  release:
    types:
      - created

defaults:
  run:
    shell: bash

jobs:
  build:
    name: "Build distribution"
    runs-on: ubuntu-latest
    steps:
      - uses: asottile/workflows/.github/actions/fast-checkout@v1.8.1

      - uses: ./.github/actions/install-dependencies
        with:
          python-version: "3.13"

      - name: "Build distribution"
        run: uv build

      - uses: actions/upload-artifact@v4
        with:
          name: release-dist
          path: dist/

  pypi-publish:
    name: "Publish to PyPI"
    runs-on: ubuntu-latest
    steps:
      - uses: asottile/workflows/.github/actions/fast-checkout@v1.8.1

      - name: Download artifact with distribution
        uses: actions/download-artifact@v4
        with:
          name: release-dist
          path: dist/

      - name: Release distribution
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
          files: dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
